package com.bhp.opusb.service.dto;

import java.util.Objects;
import java.util.UUID;

import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModelProperty;

/**
 * A DTO for the {@link com.bhp.opusb.domain.ADTable} entity.
 */
public class ADTableDTO extends AbstractAuditingDTO {

    private static final long serialVersionUID = 1L;

    private Long id;

    private UUID uid;

    @NotNull
    private String name;

    private Boolean view;

    /**
     * Indicates that this is a high volumed table. Thus, first show the search
     * form when entering the window.
     */
    @ApiModelProperty(value = "Indicates that this is a high volumed table. Thus, first show the search form when entering the window.")
    private Boolean highVolume;

    /**
     * Target API endpoint for the CRUD operations. It's initially generated by the
     * dbSync process.
     * updatable = true.
     */
    @ApiModelProperty(value = "Target API endpoint for the CRUD operations. It's initially generated by the dbSync process. updatable = true.")
    private String targetEndpoint;

    private Boolean active;

    private Long adOrganizationId;
    private String adOrganizationName;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UUID getUid() {
        return uid;
    }

    public void setUid(UUID uid) {
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean isView() {
        return view;
    }

    public void setView(Boolean view) {
        this.view = view;
    }

    public Boolean isHighVolume() {
        return highVolume;
    }

    public void setHighVolume(Boolean highVolume) {
        this.highVolume = highVolume;
    }

    public String getTargetEndpoint() {
        return targetEndpoint;
    }

    public void setTargetEndpoint(String targetEndpoint) {
        this.targetEndpoint = targetEndpoint;
    }

    public Boolean isActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Long getAdOrganizationId() {
        return adOrganizationId;
    }

    public void setAdOrganizationId(Long aDOrganizationId) {
        this.adOrganizationId = aDOrganizationId;
    }

    public String getAdOrganizationName() {
        return adOrganizationName;
    }

    public void setAdOrganizationName(String adOrganizationName) {
        this.adOrganizationName = adOrganizationName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ADTableDTO aDTableDTO = (ADTableDTO) o;
        if (aDTableDTO.getId() == null || getId() == null) {
            return false;
        }
        return Objects.equals(getId(), aDTableDTO.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getId());
    }

    @Override
    public String toString() {
        return "ADTableDTO{" +
            "id=" + getId() +
            ", uid='" + getUid() + "'" +
            ", name='" + getName() + "'" +
            ", view='" + isView() + "'" +
            ", highVolume='" + isHighVolume() + "'" +
            ", targetEndpoint='" + getTargetEndpoint() + "'" +
            ", active='" + isActive() + "'" +
            ", adOrganizationId=" + getAdOrganizationId() +
            "}";
    }
}
